yarnPath: .yarn/releases/yarn-3.2.0.cjs
nodeLinker: "node-modules"
npmScopes:
  "data-bharat":
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.pkg.github.com"
   "data-bharat":
    npmAlwaysAuth: true
    npmRegistryServer: "https://registry.yarnpkg.com"
