yarnPath: .yarn/releases/yarn-3.2.0.cjs
nodeLinker: "node-modules"

npmPublishAccess: "public"
npmScopes:
  "data-bharat":
   npmAlwaysAuth: false
   npmPublishRegistry: "https://registry.yarnpkg.com"
       