yarnPath: .yarn/releases/yarn-3.2.0.cjs
nodeLinker: "node-modules"

npmRegistryServer: "https://registry.yarnpkg.com"
npmPublishAccess: public
npmScopes:
  "data-bharat":
    npmAlwaysAuth: false
    npmRegistryServer: 
     "https://npm.pkg.github.com"
       