yarnPath: .yarn/releases/yarn-3.2.0.cjs
nodeLinker: "node-modules"

npmScopes:
  "yarn":
   npmAlwaysAuth: false
   npmPublishAccess: "public"
   npmPublishRegistry: "https://registry.yarnpkg.com"
  "npm":
   npmAlwaysAuth: false
   npmPublishAccess: "public"
   npmPublishRegistry: https://registry.npmjs.org
       